### ISSUE TITLE
Reading png files on a Mac crashes R

### ISSUE THREAD

**Issue by IanRayner** [jefferis/readbitmap#2]
I don't really understand how package dependencies work, but I have a sneaking suspicion that the problem is actually with the "png" package rather than readbitmap, but I get no response from the "png" package person (Peter Urbanek), so I thought I might try here! Apologies if that is inappropriate.

Whenever I try to load a png file using readbitmap, using either RStudio and R GUI, R crashes with a memory fault. I ended up here because I understand package imager makes use of readbitmap, and imager's load.image() function causes R to crash.

Let me know what info I can provide to help.

**Comment by jefferis** [comment]
You should try reading your png file directly with the png package directly to confirm your hunch that this is not directly to do with readbitmap. Very likely this is due to a mismatch between the compiled code in the png package and your system libpng.  Reinstalling one or both of those will likely fix. I would suggest that you reinstall the png package from source.

If that fails, then a sample png file and the result of devtools::session_info() would help to start debugging.

**Comment by jefferis** [comment]
I hadn’t realised that you’d created two separate issues for imager and readbitmap. I would close one after adding a link to the other and taking the steps described above.

**Comment by IanRayner** [comment]
Following your suggestions above:

> remove.packages(c("imager", "readbitmap", "png"))
Removing packages from ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library’
(as ‘lib’ is unspecified)
> install.packages("png")
trying URL 'http://cran.revolutionanalytics.com/bin/macosx/el-capitan/contrib/3.4/png_0.1-7.tgz'
Content type 'application/octet-stream' length 351441 bytes (343 KB)
==================================================
downloaded 343 KB


The downloaded binary packages are in
	/var/folders/t9/y75b3f650ws4k7h3ypgw8mxr0000gn/T//RtmpBEYWQf/downloaded_packages

> readPNG("Rlogo.png")

And it works!!! OMG. I had tried re-installing the packages with no luck. Well, looks like you lead me to the solution. Thank you!
